// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbmxmdqilkaopebucieh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdibXhtZHFpbGthb3BlYnVjaWVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTE5MjMsImV4cCI6MjA3MTA4NzkyM30.G_0MIlzaTA_EB0XIRqoBAYtFRwehuVQd0v7dXoYR7no";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});